import type { Metadata } from "next";
import LegalPage, { Section } from "@/components/LegalPage";
import { POLICY_REVISED, SITE_NAME } from "@/lib/site";

export const metadata: Metadata = {
  title: `Terms of use — ${SITE_NAME}`,
  description: `The terms that apply when you use ${SITE_NAME}: what the service is, what it is not, and what you are responsible for.`,
  alternates: { canonical: "/terms" },
  openGraph: {
    title: `Terms of use — ${SITE_NAME}`,
    description: "What the service is, what it is not, and what you are responsible for.",
    url: "/terms",
  },
};

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms of use"
      intro={`These terms describe what ${SITE_NAME} actually is. They are written to be read, not to be protective boilerplate; where something is genuinely your responsibility, it says so.`}
      updated={POLICY_REVISED}
    >
      <Section title="What this is">
        <p>
          {SITE_NAME} is a web client for third-party AI models. It is a tool: it sends what you type to a model
          provider you configure and shows you what comes back, alongside a set of utilities that run entirely in
          your browser.
        </p>
        <p>
          It is <strong>not</strong> a model provider, and it does not host the models. It is not affiliated with
          OpenAI or with any model provider whose name appears in the interface. Model names and logos belong to
          their respective owners.
        </p>
      </Section>

      <Section title="Your account and your keys">
        <ul>
          <li>
            You are responsible for activity under your account, including keeping your sign-in credentials to
            yourself.
          </li>
          <li>
            <strong>API keys are your responsibility.</strong> If you enter your own key it is stored in your
            browser and sent with each request. Do not enter a key on a machine you do not control, and revoke any
            key you think may have been exposed.
          </li>
          <li>You must be old enough to enter a binding contract where you live, and at least 13 years old.</li>
        </ul>
      </Section>

      <Section title="Acceptable use">
        <p>Do not use the service to:</p>
        <ul>
          <li>break the law, or infringe anyone&apos;s rights, including privacy, copyright or IP rights;</li>
          <li>harass, abuse or harm anyone;</li>
          <li>
            submit content you do not have the right to submit, or attempt to use the service to build or train
            something that violates a provider&apos;s terms;
          </li>
          <li>
            probe, scan or overload the hosting provider or any upstream API, circumvent rate limits, or interfere
            with other people&apos;s use of the service.
          </li>
        </ul>
        <p>
          The image download tool fetches a URL you supply from our server. It is restricted to public addresses
          and refuses internal ones, but you are still responsible for only using it on things you have the right
          to fetch.
        </p>
      </Section>

      <Section title="No warranty">
        <p>
          The service is provided <strong>&quot;as is&rdquo;</strong>, without warranties of any kind, express or
          implied, including fitness for a particular purpose. It may be changed, interrupted or withdrawn at any
          time.
        </p>
        <p>
          Model output is generated by a third party. It is frequently wrong, and it is not advice. Do not rely on
          it for medical, legal, financial or safety-critical decisions without independent verification by a
          qualified professional.
        </p>
      </Section>

      <Section title="Limitation of liability">
        <p>
          To the fullest extent the law allows, the operators of {SITE_NAME} are not liable for indirect, incidental,
          special or consequential loss, or for lost data, lost profits or service interruption, arising from your
          use of the service or of any model you reach through it. Nothing here excludes liability that cannot
          lawfully be excluded.
        </p>
      </Section>

      <Section title="Your content">
        <p>
          You keep ownership of everything you write and upload. You grant only the narrow permission needed to
          operate the service: to transmit your content to the provider you configured so a reply can be produced,
          and to store it in your own browser so the conversation persists. We do not claim ownership of your
          conversations and we do not use them to train anything.
        </p>
        <p>
          Be aware that a model provider&apos;s own terms also apply to whatever you send it, including its
          retention practices. That is outside our control.
        </p>
      </Section>

      <Section title="Availability and changes">
        <p>
          Features may be added, changed or removed. The tools, models and providers listed are not a commitment to
          keep any of them. If a change materially affects you, the commit history for this site is public and the
          behaviour of any version can be inspected.
        </p>
      </Section>

      <Section title="Third-party services">
        <p>
          The service relies on third parties, including the hosting provider, the authentication provider and
          whichever model provider you configure. Your use of those services is governed by their terms, and we do
          not control them.
        </p>
      </Section>

      <Section title="Ending use">
        <p>
          You may stop using the service at any time; because your data lives in your browser, clearing the site
          data removes it. We may restrict or block access where use appears to be abusive or unlawful.
        </p>
      </Section>

      <Section title="Contact">
        <p>
          Questions about these terms go to the <a href="/contact">contact page</a>. How the software handles your
          data is set out in <a href="/privacy">Data &amp; privacy</a>.
        </p>
      </Section>
    </LegalPage>
  );
}
